name: gomoku_client
description: Generated, versioned Serverpod client for Gomoku.
publish_to: none
version: 1.0.0
environment:
  sdk: ^3.13.0
resolution: workspace
dependencies:
  serverpod_auth_idp_client: 3.4.13
  serverpod_client: 3.4.13
